config/routes.rb
Rails.application.routes.draw do
  # resources :comments !! OBE due to action cables!!
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  # resources :portmanteaus
 # problem with resources above is the show action requires portmanteaus/id, which is plural!
  # ergo, customize it with portmanteau/:id
  resources :portmanteaus, except: [:show] do
    put :sort, on: :collection
  end
  #as is used for a link_to tag on index
  get 'portmanteau/:id', to: 'portmanteaus#show', as: 'portmanteau_show'
  
  # static pages
  # get 'pages/home'

  # url, controller#action'
  get 'about', to: 'pages#about'
  # get 'pages/contact'..orig, replaced by below so user doesn't requre added pages to view content
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  # your can add any custom url
  get 'about-me', to: 'pages#about'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  #action cable
  # create a web socket connection..remove resouces cables now
  # websockets different from HTTP, no resources routes needed, 
  # direct feed into Redis DB, open up a websocket connection, wrap entire route into ActionCable server
  mount ActionCable.server => "/cable"

  #this is the home page of the application
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
  extend FriendlyId
  belongs_to :topic
  has_many :comments, dependent: :destroy
  enum status: { draft: 0, published: 1 }
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:edit, :update, :destroy, :toggle_status]
  layout "blog"
  # access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all
#  access all: [:show, :index], user: all: [:new, :create {except: [:destroy,:update, :edit, :toggle_status]}, site_admin: :all

  # GET /blogs
  # GET /blogs.json
  def index
    #@blogs = Blog.all
    @blogs = Blog.page(params[:page]).per(5)
    # @page_title = "My Portmanteau | Blog Section"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    # add includes since related now and better perf..only hit db once for all comments
    # @blog = Blog.includes:comments).friendly.find(params[:id])
    @blog = Blog.includes(:comments).find_by_slug(params[:id])
    # create a new instance
    @comment = Comment.new

    @page_title = @blog.title
    @seo_keywords = @blog.body
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @blog.topic = Topic.last

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    # puts "testing"
    # byebug - stop system here during runtime, goto console, run query, check params0
    if @blog.draft?
      @blog.published!
    else
      @blog.draft!
    end
    redirect_to blogs_url, notice: 'Post status has been updated.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      # @blog = Blog.friendly.find(params[:id])
      @blog = Blog.find_by(slug: params[:id])
      # @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body, :topic_id, :status)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def gravatar_helper user
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width:40
  end
end

app/views/blogs/_blog.html.erb
<div class="blog-post">
  <h2 class="blog-post-title"><%= link_to blog.title, blog %></h2>
  <p class="blog-post-meta">Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago </p>
  
  <% if logged_in?(:site_admin) %>
    <p class="blog-post-meta">
      <%= link_to blog.status, toggle_status_blog_path(blog)  %> /
      <%= link_to 'Edit', edit_blog_path(blog) %> /
      <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }%>
    </p>
  <% end %>

  <p>
  <%= blog.body %>
  </p>
</div>

app/views/blogs/_blog_ruler.html.erb
<hr/>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <% blog.errors.full_messages.each do |message| %>
      <%= alert_generator message %>
      <%#= js add_gritter(message, title: "Error", sticky: false) %>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= form.text_field :title, class: 'form-control', placeholder: 'Title' %>
  </div>

  <div class="form-group">
    <%= form.text_area :body, class: 'form-control', rows: 15, placeholder: 'Content' %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="col-md-8 blog-main">


<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/index.html.erb
<div class="col-sm-8 blog-main">
  <%= paginate @blogs %>
 
  <%= render @blogs %>
  
  <%= paginate @blogs %>

</div>

app/views/blogs/new.html.erb
<div class="col-md-8 blog-main">
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/show.html.erb
<div class="col-md-8 blog-main">

  <h2><%= @blog.title %></h2>
  <%= link_to 'Edit', edit_blog_path if logged_in?(:site_admin) %>

  <p>
  <%= @blog.body %>
  </p>

  <%= render 'comments/comment_form'%>
  <div id= "comments" data-blog-id="<%=@blog.id %>">
    <%= render @blog.comments %>
  </div>

</div>