config/routes.rb
Rails.application.routes.draw do
  # resources :comments !! OBE due to action cables!!
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  # resources :portmanteaus
 # problem with resources above is the show action requires portmanteaus/id, which is plural!
  # ergo, customize it with portmanteau/:id
  resources :portmanteaus, except: [:show] do
    put :sort, on: :collection
  end
  #as is used for a link_to tag on index
  get 'portmanteau/:id', to: 'portmanteaus#show', as: 'portmanteau_show'
  
  # static pages
  # get 'pages/home'

  # url, controller#action'
  get 'about', to: 'pages#about'
  # get 'pages/contact'..orig, replaced by below so user doesn't requre added pages to view content
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  # your can add any custom url
  get 'about-me', to: 'pages#about'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  #action cable
  # create a web socket connection..remove resouces cables now
  # websockets different from HTTP, no resources routes needed, 
  # direct feed into Redis DB, open up a websocket connection, wrap entire route into ActionCable server
  mount ActionCable.server => "/cable"

  #this is the home page of the application
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_alerts.html.erb
<!-- gritter..not working due to jquery integration -->

<% if flash[:alerts] %>
  <%= js add_gritter(flash[:alert], :title => "Please alert this!", sticky: false) %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], :title => "Please fix error !",sticky: false ) %>
<% else %> 
  <%= js add_gritter(flash[:notice], :title => "Please notice me!",sticky: false ) %>
<% end %>

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p class="app-footer"> <%= @copyright %></p>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
  <header class="masthead mb-auto">
    <div class="inner">
      <h3 class="masthead-brand"> Matt Zickel </h3>
      <nav class="nav nav-masthead app-nav justify-content-center">
        <%= nav_helper 'nav-link', 'span' %>
        <%= login_helper("nav-link") %>
      </nav>
    </div>
  </header>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
  <%= @copyright %>
  </p>
  <p><a href="#">Back to top</a></p>
</footer>

app/views/shared/_blog_masthead.html.erb
  <div class="jumbotron p-4 p-md-5 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
      <h1 class="display-4 font-italic">The Bootstrap Blog</h1>
      <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what’s most interesting in this post’s contents.</p>
      <p class="lead mb-0"><a href="#" class="text-white font-weight-bold">Continue reading...</a></p>
    </div>
  </div>

app/views/shared/_blog_nav.html.erb
<div class="container">
  <header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 d-flex justify-content-end align-items-center">
        <a class="text-muted" href="#" aria-label="Search">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24" focusable="false"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"/><path d="M21 21l-5.2-5.2"/></svg>
        </a>
        <a class="btn btn-sm btn-outline-secondary" href="#">Sign up</a>
        <a class="btn btn-sm btn-outline-secondary" href="#">Fix in shared, slash blog_nav</a>
      </div>
    </div>
  </header>

  <div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex">
      <%= nav_helper'nav-link', 'span' %>
      <%= login_helper "nav-link" %>
    </nav>
 </div>
</div>

app/views/shared/_blog_sidebar.html.erb
     <aside class="col-md-4 blog-sidebar">
      <div class="p-4 mb-3 bg-light rounded">
        <h4 class="font-italic">About</h4>
        <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
      </div>

      <div class="p-4">
        <h4 class="font-italic">Archives</h4>
        <ol class="list-unstyled mb-0">
          <li><a href="#">March 2014</a></li>
          <li><a href="#">February 2014</a></li>
          <li><a href="#">January 2014</a></li>
          <li><a href="#">December 2013</a></li>
          <li><a href="#">November 2013</a></li>
          <li><a href="#">October 2013</a></li>
          <li><a href="#">September 2013</a></li>
          <li><a href="#">August 2013</a></li>
          <li><a href="#">July 2013</a></li>
          <li><a href="#">June 2013</a></li>
          <li><a href="#">May 2013</a></li>
          <li><a href="#">April 2013</a></li>
        </ol>
      </div>

      <div class="p-4">
        <h4 class="font-italic">Elsewhere</h4>
        <ol class="list-unstyled social-links">
          <li><a href='#'><%= fa_icon "github" %></a></li>
          <li><a href='#'><%= fa_icon "instagram" %></a></li>
          <li><a href='#'><%= fa_icon "twitter" %></a></li>
          <li><a href='#'><%= fa_icon "facebook" %></a></li>
        </ol>
      </div>
    </aside><!-- /.blog-sidebar -->

app/views/shared/_nav.html.erb
 <div class ="<%= location %>">
    <div><%=link_to "Home", root_path %></div>
    <div><%=link_to "About", about_me_path %></div>
    <div><%=link_to "Contact", contact_path %></div>
    <div><%=link_to "Blogs", blogs_path %></div>
    <div><%=link_to "Portfolios", portmanteaus_path %></div>
  </div>

app/views/shared/_portmanteau_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to 'View All Portfolio Items', portmanteaus_path %> /
    <a href="#">Back to top</a>
    </p>
    <p>
    <%= @copyright %>
  </div>
</footer>

app/views/shared/_portmanteau_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1>My Portfolio</h1>
    <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
    <p>
    <%- link_to 'Find out more about me', about_me_path, class: 'btn btn-primary' %>
    <%- link_to 'My Thoughts', blogs_path, class: 'btn btn-secondary' %>
    </p>
  </div>
</section>

app/views/shared/_portmanteau_nav.html.erb
<!-- navigation -->
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Explore</h4>
          <ul class="list-unstyled">
            <%= nav_helper 'text-white', 'li' %>
            <li><%= login_helper('text-white') %></li>

            <li><a href="#" class:"text-white">Follow on Twitter</a></li>
            <li><a href="#" class:"text-white">Like on Facebook</a></li>
            <li><a href="#" class:"text-white">Email me</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Matt Zickel</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>
<!-- end navigation -->