config/routes.rb
Rails.application.routes.draw do
  # resources :comments !! OBE due to action cables!!
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  # resources :portmanteaus
 # problem with resources above is the show action requires portmanteaus/id, which is plural!
  # ergo, customize it with portmanteau/:id
  resources :portmanteaus, except: [:show] do
    put :sort, on: :collection
  end
  #as is used for a link_to tag on index
  get 'portmanteau/:id', to: 'portmanteaus#show', as: 'portmanteau_show'
  
  # static pages
  # get 'pages/home'

  # url, controller#action'
  get 'about', to: 'pages#about'
  # get 'pages/contact'..orig, replaced by below so user doesn't requre added pages to view content
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  # your can add any custom url
  get 'about-me', to: 'pages#about'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  #action cable
  # create a web socket connection..remove resouces cables now
  # websockets different from HTTP, no resources routes needed, 
  # direct feed into Redis DB, open up a websocket connection, wrap entire route into ActionCable server
  mount ActionCable.server => "/cable"

  #this is the home page of the application
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/portmanteau.rb
class Portmanteau < ApplicationRecord
  # include Placeholder #replaced with carrierwave-aws

  has_many :technologies
  # choose technology to include when creating updating portfolio and
  # add validation to not include the technology if the name is blank
  accepts_nested_attributes_for :technologies, allow_destroy: true,
                                reject_if: lambda{ |attrs| attrs['name'].blank? }

  validates_presence_of :title, :body#, :main_image, :thumb_image

  mount_uploader :thumb_image, PortmanteauUploader
  mount_uploader :main_image, PortmanteauUploader

  def self.activities
    where(subtitle: 'Activities')
  end
 
  # preferred way
  # Pormanteau.portolio_activities
  scope :portfolio_activities, lambda {where(subtitle: 'Activities')}

  # callback to set defaults, runs when a new is created
  # after_initialize :set_defaults

# replaced by s3 carrierwave imple
  #  def set_defaults
#   # self.main_image ||=  Placeholder.image_generator(height:"600", width: "400")
#   # self.thumb_image ||=  Placeholder.image_generator(height:"350", width: "200")
#
#   self.main_image ||=  Placeholder.image_generator("600","400")
#   self.thumb_image ||=  Placeholder.image_generator("350", "200")
#
##    self.main_image ||= "http://placehold.it/600x400" 
##    self.thumb_image ||= "http://placehold.it/350x200"
#  end
#
  # for drag and drop interface
  def self.by_position
    order("position ASC")
  end
end

app/controllers/portmanteaus_controller.rb
class PortmanteausController < ApplicationController
  before_action :set_portmanteau, only: [:show, :edit, :update, :destroy, :toggle_status]
  layout "portmanteau"
  # access all: [:show, :index], user: {except: [:destroy, :sort, :new, :create, :update, :edit]}, site_admin: :all
  access all: [:show, :index, :update, :new, :edit, :sort], user: {except: [:destroy]}, site_admin: :all

  def index
    # @portfolio_items= Portmanteau.all
   #  @portmanteaus = Portmanteau.all
#     @portmanteaus = Portmanteau.order("position ASC")
    @portmanteaus = Portmanteau.by_position
    @page_title = "My Portmanteau | Portfolio Section"

  end

  # not implemented on client yet..webpacker issue
  def sort
    params[:order].each do |key, value|
      Portmanteau.find(value[:id]).update(position: value[:position])
    end
    render nothing: true
  end

  def new
#   @portfolio = Portmanteau.new
   @portmanteau = Portmanteau.new
   #used for nested attr
#   3.times {@portmanteau.technologies.build }
  end
  
  def create
    @portmanteau= Portmanteau.new(portmanteau_params)
    # @portmanteau= Portmanteau.new(params.require( :portmanteau).permit(g
    #  :title, :subtitle, :body,technologies_attributes: [:name]))
    respond_to do |format|
      if @portmanteau.save
        format.html { redirect_to portmanteaus_path, notice: 'Your portfolio is now live' }
      else
        format.html { render :new, notice: 'Saving Portmanteau failed!' }
      end
    end
  end

  def edit
    # puts @portmanteau.inspect
  end

  def show
  end

  def destroy
    @portmanteau.destroy
    respond_to do |format|
      format.html { redirect_to portmanteaus_url, notice: 'Portfolio was successfully destroyed.' }
    end
  end

  def update
    respond_to do |format|
      if @portmanteau.update(portmanteau_params)
        format.html { redirect_to portmanteaus_path, notice: 'Portfolio was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def tech_news
   @tweets = SocialTool.twitter_search
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portmanteau
      @portmanteau = Portmanteau.find(params[:id])
    end

    def portmanteau_params
      params.require(:portmanteau).permit(:title,
                                          :subtitle,
                                          :body,
                                          :main_image,
                                          :thumb_image,
                                          technologies_attributes: [:id,:name, :_destroy])
    end

end

app/helpers/portmanteaus_helper.rb
module PortmanteausHelper
  def image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end

  def portfolio_img img, type
   if img
     retrurn img.model.main_image? || img.model.thumb_image?
   else
     if type == 'thumb'
      image_generator(height:"350", width:"200")
    else
      image_generator(height:"600", width:"400")
    end
   end
  end
end
#    self.main_image ||=  Placeholder.image_generator("600","400")
#   self.thumb_image ||=  Placeholder.image_generator("350", "200")

app/views/portmanteaus/_form.html.erb
<%= form_with(model: @portmanteau, local: true) do |form| %>
  <% if @portmanteau.errors.any? %>
    <% @portmanteau.errors.full_messages.each do |message| %>
      <%= alert_generator message %>
      <%#= js add_gritter(message, title: "Error", sticky: false) %>
    <% end %>
  <% end %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :subtitle %>
        <%= form.text_field :subtitle, class: 'form-control'%>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
         Upload a main image file <%= form.file_field :main_image, style: "display:none;" %>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
         Upload a thumb image file <%= form.file_field :thumb_image, style: "display:none;" %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :body%>
        <%= form.text_area :body, rows: 13, class: 'form-control' %>
      </div>
    </div>
  </div>

    <hr>
    <div class="col-md-12">
      <h2> Technologies Used: </h2>
      <div>
        <%= form.fields_for :technologies do |tech_form| %>
          <%=  render 'technology_fields', form: tech_form %>
        <% end %>

        <div>
          <%= link_to_add_association 'Add Technology Fields', form, :technologies %>
      </div>

      <div class="form-group">
        <%= form.submit 'Save Portfolio Item', class: 'btn btn-primary btn-block' %>
      </div>
    </div>
  <% end %>

app/views/portmanteaus/_portmanteau.html.erb
<div class="col-md-4">
  <div class="card mb-4 shadow-sm" data-id ="<%= portmanteau.id %>">
    <p><%= image_tag portfolio_img(portmanteau.thumb_image.url,'thumb') unless portmanteau.thumb_image.nil? %> </p>
    <div class="card-body">
      <span><%= link_to portmanteau.title, portmanteau_show_path(portmanteau.id) %> </span><%= portmanteau.subtitle %>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
          <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
        </div>
        <small class="text-muted">9 mins</small>
      </div>
    </div>
  </div>
</div>

app/views/portmanteaus/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control'%>
  <%= link_to_remove_association "Remove Technologes", f %>
</div>

app/views/portmanteaus/edit.html.erb
<div class="container">
<h1>Edit this Portfolio Item </h1>
  <%= render 'form', portmanteau: @portmanteau %>
</div>

app/views/portmanteaus/index.html.erb
<main role="main">
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
        <!--<a href="portmanteaus/new">Create New Portfolio </a> -->

      <%#= link_to "Create New Item", new_portmanteau_path %>

      <%# this is the relative path, use most of the time %>

      <p>
      <%#=  new_portmanteau_path %>
      </p>

      <%# this is the absolute path, use for emails %>

      <p>
      <%# =  new_portmanteau_url%>
      </p>

      <%= render partial: 'portmanteau', collection: @portmanteaus %>
    </div>
    </div>
  </div>
</main>

app/views/portmanteaus/new.html.erb
<div class="container">
<h1> Create a new Portfolio </h1>
<%= render 'form', portmanteau: @portmanteau %>
</div>

app/views/portmanteaus/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7">
      <p><%= image_tag portfolio_img(@portmanteau.main_image.url,'main') unless @portmanteau.main_image.nil? %> </p>
    </div>
    <div class="col-md-5">
      <h1><%= @portmanteau.title %></h1>
      <hr>
      <em><%= @portmanteau.subtitle %></em>

      <p><%= @portmanteau.body%> </p>

      <hr>

      <h3>Technologies Used </h3>
      <% @portmanteau.technologies.each do |t| %>
        <p> <%= t.name %> </p>
      <% end %>

      <% if logged_in?(:site_admin) %>
        <div class="col-md-12">
        <%= link_to "Edit Item", edit_portmanteau_path(@portmanteau), class: 'btn btn-warning' %>
        </div>
      <% end %>

    </div>
  </div>
</div>

<%#= params.inspect %>
<%#= session.inspect %>